kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-sc
  namespace: app-mysql
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
storagepolicyname: "vSAN Default Storage Policy" #
#csi.storage.k8s.io/fstype: "nfs4" # Optional Parameter
