apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    name: app-mysql
  namespace: app-mysql
spec:
  storageClassName: csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
