---
apiVersion: v1
kind: Service
metadata:
  name: acmefit-lb
  labels:
    app: acmefit
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: acmefit
    tier: frontend
    service: frontend
