apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  labels:
    name: acme-fitness
spec:
  storageClassName: csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
