apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yelb-http-ingress
  labels:
    app: yelb
spec:
  ingressClassName: avi-lb
  rules:
    - host: yelbinscure.apps.ocp-cl01.vmware.ocpeval.scstec.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: yelb-ui-svc-np
              port:
                number: 80
