apiVersion: route.openshift.io/v1
kind: Route
metadata:
 name: yelb-route
spec:
 host: yelbroute.apps.ocp-cl03.vmware.ocpeval.scstec.net
 path: /
 to:
   kind: Service
   #name: yelb-ui
   name: yelb-ui-cip
