kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  #storagepolicyname: "NFS Storage Policy"
  storagepolicyname: "NFS Storage Policy"
  fstype: ext4
